const INXT_AI_URL = 'https://ai.internxt.com';
const INXT_DRIVE_URL = 'https://drive.internxt.com';
const INXT_URL = 'https://internxt.com';
const INXT_BLOG = 'https://blog.internxt.com';
const INXT_SUPPORT = 'https://help.internxt.com';
const INXT_GITHUB = 'https://github.com/internxt';

const urls = {
  home: `${INXT_URL}`,
  pricing: `${INXT_URL}/pricing`,
  products: {
    drive: `${INXT_URL}/drive`,
    objectStorage: `${INXT_URL}/cloud-object-storage`,
    vpn: `${INXT_URL}/vpn`,
    antivirus: `${INXT_URL}/antivirus`,
    cleaner: `${INXT_URL}/cleaner`,
    meet: `${INXT_URL}/meet`,
    ai: `${INXT_AI_URL}`,
    business: `${INXT_URL}/business`,
    family: `${INXT_URL}/family`,
    send: 'https://send.internxt.com',
  },
  company: {
    privacy: `${INXT_URL}/privacy`,
    openSource: `${INXT_URL}/open-source`,
    sustainability: `${INXT_URL}/green-cloud-computing`,
    about: `${INXT_URL}/about`,
    certifications: `${INXT_URL}/cloud-data-centers`,
    legal: `${INXT_URL}/legal`,
    mediaArea: `${INXT_URL}/media-area`,
    security: 'https://blog.internxt.com/how-internxt-protects-your-data',
  },
  join: {
    affiliates: `${INXT_URL}/affiliates`,
    github: 'https://github.com/internxt',
    login: `${INXT_DRIVE_URL}/login`,
    newsletter: `${INXT_URL}/newsletter-subscribe`,
    signup: `${INXT_DRIVE_URL}/new`,
    storageForEducation: `${INXT_URL}/cloud-storage-for-education`,
    support: 'https://help.internxt.com',
    whitePaper: '/whitepaper/internxt-white-paper-1.pdf',
  },
  legal: `${INXT_URL}/legal`,
  login: `${INXT_DRIVE_URL}/login`,
  features: {
    privateCloud: `${INXT_URL}/private-cloud-storage-solutions`,
    cloudBackup: `${INXT_URL}/cloud-storage-backup-solutions`,
    gdprCloud: `${INXT_URL}/gdpr-cloud-storage`,
    cloudPhotos: `${INXT_URL}/cloud-storage-for-photos`,
    cloudVideos: `${INXT_URL}/cloud-storage-for-videos`,
    lifetime: `${INXT_URL}/lifetime`,
    freeCloudStorage: `${INXT_URL}/drive/free-cloud-storage`,
  },
  resources: {
    blog: 'https://blog.internxt.com/',
    cyberAwareness: `${INXT_URL}/cyber-awareness`,
    storageComparison: `${INXT_URL}/cloud-storage-comparison`,
    whatGoogleKnows: `${INXT_URL}/what-does-google-know-about-me`,
    webdav: `${INXT_URL}/webdav-rclone`,
    nas: `${INXT_URL}/nas`,
    coupons: `${INXT_URL}/coupons`,
    reviews: `${INXT_URL}/reviews`,
    alternatives: {
      pCloud: `${INXT_URL}/pcloud-alternative`,
      dropbox: `${INXT_URL}/dropbox-alternative`,
      mega: `${INXT_URL}/mega-alternative`,
      koofr: `${INXT_URL}/koofr-alternative`,
      icedrive: `${INXT_URL}/icedrive-alternative`,
      onedrive: `${INXT_URL}/onedrive-alternative`,
      googleDrive: `${INXT_URL}/google-drive-alternative`,
      drime: `${INXT_URL}/drime-alternative`,
      degoo: `${INXT_URL}/degoo-alternative`,
      filejump: `${INXT_URL}/filejump-alternative`,
      elephantdrive: `${INXT_URL}/elephantdrive-alternative`,
      sync: `${INXT_URL}/sync-alternative`,
      filen: `${INXT_URL}/filen-alternative`,
      idrive: `${INXT_URL}/idrive-alternative`,
      terabox: `${INXT_URL}/terabox-alternative`,
      proton: `${INXT_URL}/proton-alternative`,
    },
    videoCalls: {
      googleMeet: `${INXT_URL}/alternative-to-google-meet`,
      zoom: `${INXT_URL}/alternative-to-zoom`,
      teams: `${INXT_URL}/teams-alternative`,
    },
    privacyDirectory: `${INXT_URL}/privacy-directory`,
  },
  social: {
    instagram: 'https://instagram.com/internxt',
    linkedin: 'https://linkedin.com/company/internxt',
    reddit: 'https://www.reddit.com/r/internxt/',
    twitter: 'https://twitter.com/Internxt',
    youtube: 'https://www.youtube.com/channel/UCW2SxWdVEAEACYuejCgpGwg/featured',
  },
  tools: {
    byteConverter: `${INXT_URL}/byte-converter`,
    fileConverter: `${INXT_URL}/file-converter`,
    passwordChecker: `${INXT_URL}/password-checker`,
    passwordGenerator: `${INXT_URL}/password-generator`,
    tempMail: `${INXT_URL}/temporary-email`,
    virusScanner: `${INXT_URL}/virus-scanner`,
    darkWebMonitor: `${INXT_URL}/dark-web-monitor`,
    metadataRemover: `${INXT_URL}/metadata-remover`,
    aiDetector: `${INXT_URL}/ai-detector`,
    fileCompressor: `${INXT_URL}/file-compressor`,
  },
  blog: `${INXT_BLOG}`,
  support: `${INXT_SUPPORT}`,
  github: `${INXT_GITHUB}`,
};

export default urls;
